name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint Check
      run: |
        pip install flake8
        flake8 . --ignore=E501,E302,E131,W292,E126,E121,E123

    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        pytest

    - name: Build Docker Image
      run: |
        docker build -t aceest-gym .